version: '3'
services:
  node-app:
    build: .
    ports:
      - "80:80"
    environment:
      - PORT=80
      - NODE_ENV=production
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_DATABASE=node-app
    volumes:
      - ./data/db:/data/db
    
