version: '3'
services:
  node-app:
    build: .
    ports:
      - "${PORT}:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=node-app
    volumes:
      - ./data/db:/data/db
    
